### ISSUE TITLE
Create repo

### ISSUE THREAD

**Issue by azrdev** [magkopian/keepassxc-debian#4]
Pre-built binary packages are a convenient thing, thank you! However, could you offer a debian repo and/or PPA so updates can be installed through the normal automatisms of debian?

**Comment by DJCrashdummy** [comment]
**well... the best would be to get it into the debian repositories!**
there is also this: https://github.com/keepassxreboot/keepassxc-packaging but i'm not sure about the progress...

**Comment by magkopian** [comment]
@azrdev I'm not really a fan of third party repos because I see them as a security risk, especially when they come from a random guy maintaining an unofficial software package. Of course I'm not saying that I have malicious intents, but when I would be the first to not trust a third party repo from a random guy on the web, wouldn't it be kind of ironic being the person to provide such a repo?

Now, I if there is a demand by at least a few people that they decide they trust me I suppose I could look into it, but unless that happens I have no plans maintaining an unofficial third party repo.

@DJCrashdummy To be completely honest, when I first put together this package my intention was to also maintain it as an official Debian package and try to find a sponsor through [mentors.debian.net](https://mentors.debian.net/) in order to get it into the official Debian repos. I didn't do that though, as the KeepassXC team has also expressed the interest of doing the packaging themselves by automatically generating a Debian source package as a part of their release script.

That was a while ago, but I assume their plans haven't changed since then. As far as I am concerned, I will keep maintaining this Debian package exactly the same way as I already do, until the KeepassXC team comes up with a better solution. As for getting this package into the official Debian repositories this is something that is not going to happen, as it gets into conflict with the as far as I know plans of the KeepassXC team.

**Comment by DJCrashdummy** [comment]
i didn't mean you have to push your package into the debian repositories, i just talked about keepassxc in general.
so it is good to hear that this is on the list, i hope this will happen anytime soon... maybe it is possible to support the keepassxc-team at this task? (also therefore i posted the link...)

for the time thank you for your work packaging keepassxc!

**Comment by magkopian** [comment]
@DJCrashdummy  As I already stated in the past, if the KeepassXC team believes that I can assist the project in any way they are free to contact me. So, since that hasn't happened yet, I assume that there isn't actually a way I can help with the official packaging. The KeepassXC team is very aware of the fact that I'm actively maintaining this package, otherwise they wouldn't link to it from their website.

Anyway, I believe there's nothing more to add on this topic, so I will go ahead and close this issue.
