### ISSUE TITLE
Version Naming

### ISSUE THREAD

**Issue by medialove** [magkopian/keepassxc-debian#7]
The names should use the actual distro release name like "jessie" etc. - "testing" is something different today than it was a few months ago, so the current naming scheme is not good.

**Comment by danwep** [comment]
It is fine the way it is now. Since one is installing the package manually. The person should know enough about Debian's releases before installing any packages and resolve any dependencies. But adding the codename to the release names would be fine I guess. Or just link to Debian's Releases page[0].

[0] https://www.debian.org/releases/

**Comment by magkopian** [comment]
I agree with @danwep and basically that was the reason why I was using `stable` instead of `jessie` on the filename for example. I don't see though how adding the codename of the release to the filename as well could be a problem, so this is what I'll do starting from the next package release.

**Comment by danwep** [comment]
Thank You for the quick reply and your work on these KeePassXC packages.
