### ISSUE TITLE
Which version to choose for Ubuntu 16.04?

### ISSUE THREAD

**Issue by medialove** [magkopian/keepassxc-debian#8]
Which of the offered versions should be used for Ubuntu 16.04 LTS? 

Thanks for your incredible work, very appreciated!

**Comment by corwin78** [comment]
Hello, version 2.1.4-1 **Stable** is working for me on Ubuntu 16.04.2. Testing or Unstable can't be installed due to the older version of libgcrypt20 in Ubuntu than is required.

**Comment by magkopian** [comment]
Ideally, a binary package for Xenial should be built, unfortunately though I had no luck with that so far. When I try to create a chroot environment by running `sudo pbuilder create --distribution xenial --mirror http://archive.canonical.com/ubuntu` for Xenial, what I get is the following output,

```
I: Distribution is xenial.
I: Current time: Mon Jun 26 19:40:47 EEST 2017
I: pbuilder-time-stamp: 1498495247
I: Building the build environment
I: running debootstrap
/usr/sbin/debootstrap
I: Retrieving InRelease 
I: Checking Release signature
I: Valid Release signature (key id 790BC7277767219C42C86F933B4FE6ACC0B21F32)
E: Invalid Release file, no valid components
E: debootstrap failed
W: Aborting with an error
I: cleaning the build env 
I: removing directory /var/cache/pbuilder/build/20797 and its subdirectories
```

If you use Ubuntu though instead of Debian like I do, you should be able to build the package yourself by following the instructions on the README. Until I find the solution to this, I can't unfortunately provide binary packages for Ubuntu, you can still though use the packages build for Debian if the work for you like @corwin78 suggested.

**Comment by corwin78** [comment]
Anyway, I can confirm that **Unstable** version is working on Ubuntu 17.04 without problem.

**Comment by manuel-uberti** [comment]
What about the new version 2.2.0?

**Comment by zsteinmetz** [comment]
On KDE neon / Ubuntu 16.04 LTS only **oldstable** worked for me. Hope this helps.

**Comment by manuel-uberti** [comment]
Thank you, @zsteinmetz, I will try that.

**Comment by and-ru** [comment]
Just as @zsteinmetz has pointed out for him, only the **oldstable** worked for me in Xubuntu 16.04.2. As I installed it using Gdebi, no missing dependencies fixes were needed. Thanks to @magkopian for building this package for Debian-based distros.

**Comment by neovatar** [comment]
@magkopian I successfully built an Ubuntu package (on a Ubuntu 16.04 system) and I may have the solution for the error you describe in https://github.com/magkopian/keepassxc-debian/issues/8#issuecomment-311119005

A use of `--mirror http://archive.canonical.com/ubuntu` for the pbuilder comman did trigger the same error. It was also necessary to specify the components. Without it, pbuilder would not install the build dependencies and fail.

The following worked for me to create an ubuntu pbuilder chroot environment:

````
sudo pbuilder create --distribution xenial \
  --components "main restricted universe multiverse" \
  --mirror http://archive.ubuntu.com/ubuntu/ubuntu
````

I was able to build the .deb afterwards with:

````
sudo pbuilder build keepassxc_2.2.0-1.dsc --distribution xenial
````

I did run this on a Ubuntu 16.04 machine tho, so you should double check on your Debian system, but it should work. I was tried to test this within a Debian docker image, but the chroot part of pbuilder did not work really well in a container and my knowledge of pbuilder is very slim.

**Comment by magkopian** [comment]
@neovatar Looks like it worked! I had to pass `--suppress-tags bad-distribution-in-changes-file` to Lintian because it was giving me an error for the distro name, but it did build with no problems. If you don't mind, could you give [this](https://www.dropbox.com/s/7ogik1lnc0pp80g/keepassxc_2.2.0-1_amd64_ubuntu_16.04.deb?dl=1) a try because I don't have an Ubuntu machine around?

Unfortunately, I still can't build for Ubuntu 17.10, because the `debootstrap` package on Stretch is a bit old. After it arrives on `stretch-backports` though, it should not be a problem.

**Comment by neovatar** [comment]
Was able to install the package and start keepassxc on Ubuntu 16.04.

What do you think about the idea of moving from debootstrap to docker containers for building the packages?

**Comment by magkopian** [comment]
I haven't thought of using Docker for building the packages, but `debootstrap` works quite well for me so I'm not really sure if it worths the time looking into something different. In fact, my main problem is the amount of time it takes for building all those packages on my desktop. For that reason, I was recently looking into the possibility of automating the building process using an external building service. 

So far, I did several attempts with [travis.debian.net](http://travis.debian.net/) but with no success. I also tried the free [openSUSE Build Service](https://build.opensuse.org/), which would allow me to build the package for Ubuntu and Debian Stable but not for Testing and Unstable.

**Comment by davidak** [comment]
It would be great if this would be packaged into a PPA for ubuntu.
I think canonical offers a build service in launchpad for PPAs.

An official debian package would be also great.

I can recommend building (deb packages) inside docker. There is also https://github.com/drone/drone which is a CI that uses docker.
